### ISSUE TITLE
Want events when overlay-trigger, sp-dropdown or sp-action-menu opene/close

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#1055]
### Expected Behaviour

This is a feature request. I'd love to get an event when menus and overlay triggers open and close. I have hit two scenarios where this would have been handy in the last week.

**Comment by cuberoot** [comment]
If this seems reasonable, I'm happy to do the work.

**Comment by Westbrook** [comment]
Totally agree. Would love to see a rough outline of your specific use cases here in the issue for reference, too.

Should this event take into account anything else about the overlay? Type, etc. My use case had always been generically "when did this close" so maybe that's the long and short of it, but having your cases might support the desire for slightly more as far as the API goes here.

Please note that "close" is currently dispatched here: https://github.com/adobe/spectrum-web-components/blob/main/packages/overlay/src/ActiveOverlay.ts#L328 and that the `next` branch is pretty far ahead of the `main` branch (due to some release blocking that hopefully #1051 will release) so it's possible that this change should be branched from there.

**Comment by cuberoot** [comment]
My two use cases are:
- I have a popover within an overlay trigger. The trigger element needs to be styled differently when the popover is open. In this case, I am using a popover to simulate an action menu to work around the issue of needing two separate lists of options in one menu
- In the second case, I have an action menu containing some non-standard controls that need to update using network requests when the menu opens

**Comment by Westbrook** [comment]
Released
