### ISSUE TITLE
[Color Slider] Add dispatchChangeEvent for input value changes

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#1469]
### Expected Behaviour
Color Slider should dispatch a change event when input values are changed. This should work [similar to Slider](https://github.com/adobe/spectrum-web-components/blob/50c8640a95baee56b5f1b74bbc66a69ef9443167/packages/slider/src/Slider.ts#L326) when the handle has focus and user tries to change values with cursor keys.

### Actual Behaviour
No change event is dispatched

#### Steps to Reproduce
Set focus to Color Slider handle
key down cursor up/down moves the handle
no change event is dispatched to outer component 

#### Platform and Version
color-slider: 0.1.4 on Chrome

**Comment by Westbrook** [comment]
Indeed it does. Easy to forget that native `<input>` elements don't have their `change` events composed and need to be re-dispatched in our case.

It appears on first look the `sp-color-wheel` shares code shape here, and will likely need this same update. However, `sp-color-area` seems to have mitigations for this. Have you see similar as part of your consumption?

**Comment by spdev3000** [comment]
I currently only use Color Area (Handle) and Color Slider - and it only happens at the Slider component. Color Area works fine for me (besides #1470).

**Comment by Westbrook** [comment]
@najikahalsema let me know if this helps to clarify the issue here.

Good Steps:
1. Visit https://webcomponents.dev/edit/jC0UwYyeK45myyAsMkYm/src/index.ts
2. Click, drag, and release the handle on any of the three controls
3. Notice that you get a stream of `input` events and one `change` event at the end

Bad Steps (area) keyboard:
1. Visit https://webcomponents.dev/edit/jC0UwYyeK45myyAsMkYm/src/index.ts
2. Visually focus the handle in the `sp-color-area` element (it should get bigger)
3. Use the arrow keys to adjust the value of the control
4. Notice the `change` event dispatched on each arrow keys, but no `input` event

Bad Steps (area) Voice Over:
1. Visit https://webcomponents.dev/edit/jC0UwYyeK45myyAsMkYm/src/index.ts
2. Visually focus the handle in the `sp-color-area` element (it should get bigger)
3. Focus the control
4. Enter the slider with `Shift + Control + Option + Down Arrow`
5. Press `Control + Option` => See the input event dispatch for some reason
6. Press `Control + Option + Arrow *` => See the change event dispatch but no `input` event

Bad Steps (slider) keyboard:
1. Visit https://webcomponents.dev/edit/jC0UwYyeK45myyAsMkYm/src/index.ts
2. Visually focus the handle in the `sp-color-slider` element (it should get bigger)
3. Use the arrow keys to adjust the value of the control
4. Notice that no events are dispatched via this interaction

Bad Steps (slider) Voice Over:
1. Visit https://webcomponents.dev/edit/jC0UwYyeK45myyAsMkYm/src/index.ts
2. Visually focus the handle in the `sp-color-slider` element (it should get bigger)
3. Focus the control
4. Enter the slider with `Shift + Control + Option + Down Arrow`
5. Press `Control + Option + Arrow *` => See the change event dispatch but no `input` event

Bad Steps (wheel) keyboard:
1. Visit https://webcomponents.dev/edit/jC0UwYyeK45myyAsMkYm/src/index.ts
2. Visually focus the handle in the `sp-color-wheel` element (it should get bigger)
3. Use the arrow keys to adjust the value of the control
4. Notice the `input` event dispatched on each arrow keys, but no `change` event
5. 
Bad Steps (wheel) Voice Over:
1. Visit https://webcomponents.dev/edit/jC0UwYyeK45myyAsMkYm/src/index.ts
2. Visually focus the handle in the `sp-color-wheel` element (it should get bigger)
3. Focus the control
4. Enter the slider with `Shift + Control + Option + Down Arrow`
5. Press `Control + Option + Arrow *` => See the change event dispatch but no `input` event

I'm somewhat impressed we were able to get this a little wrong a little different each time 🙈. It's possible that the Voice Over issues clean up with the keyboard issues, anyways, but if needed this can be 6 different changes. We should start with `Bad Steps (slider) keyboard` to unblock @spdev3000 and get #1526 moving forward, but hopefully that work clarifies the steps to address the rest of these.

**Comment by najikahalsema** [comment]
> Bad Steps (area) keyboard:
> 
> Visit https://webcomponents.dev/edit/jC0UwYyeK45myyAsMkYm/src/index.ts
> Visually focus the handle in the sp-color-area element (it should get bigger)
> Use the arrow keys to adjust the value of the control
> Notice the change event dispatched on each arrow keys, but no input event

@Westbrook A change event should dispatch on each keyboard event? I only get one, if any at all.

**Comment by najikahalsema** [comment]
Nvm. As usual, I cannot read.

**Comment by najikahalsema** [comment]
I think this definitely helps clarify things and gives good direction for next steps. I agree, we should address the keyboard issue first. I'll get on it!
