### ISSUE TITLE
sp-number-field should allow language specification

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#1495]
### Expected Behaviour

We need to be able to override the `navigator.language` for number formatting when using `sp-number-field`. 

### Actual Behaviour

We can specify the number format options, but not the actual language. It is locked to `navigator.language`

**Comment by cuberoot** [comment]
See comment here: https://github.com/adobe/spectrum-web-components/pull/1416/files#r642344048

**Comment by Westbrook** [comment]
@cuberoot can you help me understand the context where this would be used? In particular, is the case for language customization that you'd like to remove formatting all together, as we see in #1497 or so that you can literally force the formatting into a language not default to the current browsing context?

In relation to the idea of setting language at the "application" level, I wonder if others see this as a good reason to further expand the responsibilities of `sp-theme` to handle/resolve this for descendent elements as well? Seems like this relates to `dir` management et al. so having this centralized would seem a good bargain. 

Relying on `sp-theme` generally implies we want to be able to mange this dynamically across the lifecycle of an application. If this were a read once situation, we could prefer `document.documentElement.lang` over `navigator.language` as an alternative. I'm not sure where an application would actually change its language without a page refresh, but I'd be happy to hear use cases we're interested to cover in that way.

**Comment by cuberoot** [comment]
Ok, here's some more information about my use case. Apparently Adobe tracks user language preferences across products and this may not be reflected in `navigator.language`. Also, we allow the user to specify the language in a query parameter in the URL.

So, I do want the language parameter to be passed to `Intl.NumberFormat`, but I want to be able to override that somehow.

Leveraging `sp-theme` seems like the right approach. It would be idea to be able to change languages on the fly, but I don't think it is a requirement. I understand that would be hard to make this dynamic.

**Comment by adixon-adobe** [comment]
To me this feels really similar to the text direction problem and `dir` handling we have. Using the [lang](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) attribute seems like the right way to solve this, and I'd view the issue as "sp-number-field isn't using the scoped lang attribute if present, instead always defaulting to navigator.language".

**Comment by spdev3000** [comment]
Just to add my 2 cents: We are currently parsing the user selected language from various sources like cookies, url params, etc. (and navigator.language as default if no other options are present). Also currently we don't give the user the option to dynamically switch languages (without reloading) - but that may change at a later point.
Seeing those different thoughts I'd agree with adixon - that this feels like a `lang` attribute similar to `dir` that may be used as source for Intl.NumberFormat.

**Comment by Westbrook** [comment]
Whipped up some options to take a look at and discuss.

In all examples you can use `document.querySelector('docs-page').shadowRoot.querySelector('sp-theme').lang = 'fr'` replacing `'fr'` with your favorite language to test them out.

### `lang` all the things
https://westbrook-lang-attr--spectrum-web-components.netlify.app/components/number-field
The adds a `lang` attribute to _every_ `SpectrumElement` based custom element, much as we have done previously with `dir`.

*Pros*
- reactive generally
- reactive to `sp-theme` or `document.documentElement` (when no `sp-theme` present) for `lang` value

*Cons*
- sprouts a `lang` attribute  into DOM
- eagerly applies `lang` and associated render to everything based on `SpectrumElement`

*Work that could be done*
- create a `_swcMetadata` property to contain this sort of information so that it can be leveraged internally but won't sprout attributes

---

### Dispatch an event on every render
https://westbrook-lang-event--spectrum-web-components.netlify.app/components/number-field
Add `lang` to `sp-theme-query` for point of need resolution.

*Pros*
- lazy
- focused to only where things are needed
- resolves to `document.documentElement.lang` or `navigator.language` when `sp-theme` not present

*Cons*
- not reactive
- resolves every time, even when no changes have occurred

*Work that could be done*
- if lazy is OK, we could only resolve it once and document a known limitation of `lang` generally not being reactive

---

### Provide `lang` context
https://westbrook-lang-context--spectrum-web-components.netlify.app/components/number-field
Provide a `lang` context on `sp-theme` that can be consumed via events. This is loosely the approach we use for resolving the theme for `code-example` elements in the docs.

*Pros*
- reactive
- lazy
- focused on only where things are needed
- doesn't repeat work

*Cons*
- not reactive to `document.deocumentElement.lang` or `navigator.language`

*Work that could be done*
- use `this.resolvedLanguage || document.deocumentElement.lang || navigator.language` to at least catch up to those values on the _next_ render
- use a self resolving context that created a Provider on `body` when `sp-theme` was not found in order to reactively bind to `document.deocumentElement.lang` or `navigator.language`
- lean closer to: https://github.com/webcomponents/community-protocols/pull/10

---

Lots of options, hopefully one of them strikes enough people's fancy to clarify a path forward. Regardless of which is taken, clean up, test, etc. will be required before we move forward with one of these. Happy to prioritize this as soon as we can come to an agreement.

For my money, I think the "context" approach is likely the best and begins to clarify a system wide approach to sharing settings without requiring them to be _everywhere_ by default. Regardless of how complex of a context we leverage for an initial release, we could iterate closer and closer to the Community Protocol version and be an example of such communication both in system wide applications but also to the broader community.

**Comment by cuberoot** [comment]
I vote for the context approach.

**Comment by spdev3000** [comment]
+1 for the lang context approach

**Comment by moisadoru** [comment]
Context would be my preference as well, mainly because apps should be in control of the locale they use in the UI (many have language selectors, so there is a good chance that the desired locale differs from the locale configured in the browser). There is also the case when the app does not support every possible locale, in which case it uses a fallback, so it does need to have full control of the locale used in the UI

Also, the reactivity would need to be handled in the context provider, eg. when the user changes language, the provider would invoke the proper context callbacks again with the new value, so every element would get a chance to update itself. This could also include non-UI elements) that have a dependency on the configured locale for some reason.

**Comment by Westbrook** [comment]
Cool. I'm good to move forward with the context approach.

Related questions: 
- With the recent release of `sp-slider-handle` the element began accepting a `language` attribute, should this pattern be applied there?
- Can I apply it whole sale and remove the `language` attribute going forward or do I need to keep supporting the attribute and the context resolution?
- There's some nice Formatter caching in Slider, would anyone been hurt if I waited for future work to apply similar caching in Number Field?

**Comment by cuberoot** [comment]
You can nuke the `language` attribute on `sp-slider` when you supply an alternative solution. We'll update our code when the API changes.

I am not concerned about formatter caching until it shows up on a performance sampling trace :-)
