### ISSUE TITLE
Number field looses focus after first key

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#1513]
### Expected Behaviour

When I click in the default storybook entry for number field, I expect to be able to type the number 100 (as per the placeholder value).

### Actual Behaviour

As soon as I type "1" the field looses focus

#### Steps to Reproduce

1. browse to https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/number-field--default
2. click in the number field
3. type '100'
4. note that the field only contains '1' and does not have focus anymore

#### Platform and Version

Chrome Dev on Mac

**Comment by Westbrook** [comment]
This comes from established Storybook keyboard shortcuts:
![image](https://user-images.githubusercontent.com/1156657/121173551-efa7dc00-c826-11eb-983f-4a3c5eebbb10.png)
I'm not sure that `sp-number-field` should manage the relationship between keys entered into it and the keys that get consumed by an application by default, but am open to thoughts in this area.

Knowing that this is an application shortcut, do you still feel that this is a bug? Do you have thoughts on how you'd want it addressed?

Specific to Stroybook, I could see having a decorator on these stories that `event.stopPropagation()`ed keyboard events outside of the element so that this didn't happen. This is likely useful in a number of other `<input>` relative contexts. Would that align with what you are hoping for here?

**Comment by cuberoot** [comment]
Ah, ok that makes sense. So, it's not a SWC bug. Now that I think about it, I have hit this issue with the slider work. So, some way of getting storybook to stop consuming keyboard events from fields would be nice.
