### ISSUE TITLE
NumberField: Support of any generic unit string

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#1715]
### Expected Behaviour
We'd like to provide a generic unit string (such as `px`) to `sp-number-field` in order to let it be appended to the current value (and not parsed by and NumberFormatter added).

For example: To achieve a Pixel NumberField with display value `1234 px` we'd like to use something like
```
<sp-number-field custom-unit="px" value="1234"></sp-number-field> 
```

### Actual Behaviour
Current NumberFormatter doesn't provide any `px`-related unit. 

#### Platform and Version
MacOs, Chrome v92 

#### Sample Code that illustrates the problem
Unfortunately this doesn't work:
```
.formatOptions=${{ useGrouping: false, unit: 'graphics-pixel', style: 'unit', unitDisplay: 'narrow' }}
```
Also - as we need to provide a localized version of `px` we'd like to see such a generic/polyfill solution.

**Comment by Westbrook** [comment]
I've looked closer at this. The polyfill version is not inherently difficult. It's just ugly and fat. Short story, to support new units inline of the `Intl.NumberFormat()` API you currently have to blow away the entire native object, have it rebuilt, and then populate it with your own information about the units that you're looking to support. To make matters worse, the polyfill is currently written in CJS. You are able to inject the local to support this on demand, which dials things back a little, and you could also choose to support less units than the actual API which would do so a little bit more, but it's still ugly and fat.

To make matters worse, I'm having a hard time seeing an actual path towards additional units actually being added to the API based on these GitHub issues:
- https://github.com/tc39/ecma402/issues/605
- https://github.com/tc39/ecma402/issues/503
- https://github.com/tc39/ecma402/issues/470
- https://github.com/tc39/proposal-unified-intl-numberformat/issues/39
I'm looking to make the right proposals and requests there, but it isn't likely something that gets into the browser soon, even if it does pass mustard. I'm also trying to find the right people on that end to discuss the possibility of an `Intl.numberFormat.create()` (as outlined in https://github.com/tc39/ecma402/issues/434) supporting or being paired with a version that loaded that locale data from user space rather than cold storage in the browser.

To help support my investigations here, are there units outside of `pixel` that you are interested in gaining support for with this request? I want to more robustly test whether any solution I propose here would hold up to a wider range of requests. Similarly, would you actually expect to leverage the `unitDisplay` property with these units or would they likely deliver in a more normalized share, e.g. could everything be `10px` and nothing be `10 pixels`.

With all of this in mind I'm taking a look at alternative approaches. The current one I'm looking into is: https://support-px--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--pixels Herein, we see the normal `formatOptions` object supplied to the Number Field as if it were fully supported by the browser, but under the covers when the these options fail we fall back to a unit-less `formatOptions` object and then optionally apply a `unit` as originally supplied in the `formatOptions` to the display text when the field is not focused. Things to note:
- none of the rest of the units are added/removed as seen here. Maybe they should be.
- this also surfaces some questions about how the visible text should be represented in aria, units or not...
- there's not currently support for pluralization, not sure how deep we would need/want to investigate supporting this.
- there's no `unitDisplay` support, only exactly what is supplied via `unit` is leveraged here, and only when `display: unit` is supplied
- this would externalize the internationalization of any string leveraged here outside of the browser defaults.
- probably some more issues that I'm not thinking about right now.

@spdev3000, let me know what you're thinking here and any added information you might be able to share about `unitDisplay` usage, pluralization, translations, etc. Thanks!

**Comment by spdev3000** [comment]
Hi @Westbrook,
First big thanks for all the deep digging into specs and formatOptions ecma issues. 
To your questions: I am currently interested into supporting `px|in|cm|mm|pt|pc` units, where I think "in, cm and mm" are already supported. Not sure about points and picas.

I like your approach of formatting the real value only and append the unit as string when necessary. Questions would be - if we need any attributes/flags to signalize such behavior or to "fail" silently as default and append this unit string. Also how to have this combined with #1514 

And to your other points:
I think we won't need `unitDisplay` (and therefore also no pluralization) at least for my use cases.
Translations would be handled from the outside, but I would like to still rely on the lang-specific formatting of numbers-only (e.g. 1,234 for DE vs. 1.234 for EN)

My other suggestions: 
- visible text should be represented in aria with units
- no pluralization
- there's no unitDisplay support, only exactly what is supplied via unit is leveraged here, and only when display: unit is supplied => ok for me
- this would externalize the internationalization of any string leveraged here outside of the browser defaults. => ok
- not sure about `none of the rest of the units are added/removed as seen here. Maybe they should be.`

**Comment by Westbrook** [comment]
I've added https://github.com/tc39/ecma402/issues/607 to track some of the spec possibilities here.

From you list here, `px`, `pt`, and `pc` (pixels, points, and picas) are not supported by `Intl.NumberFormat` by default. Am I correct in assuming here that you'd leverage the "short" or two character unit? I'll work on expanding the demos to make sure everything works across those examples to start leveraging your notes on my current approach. Hopefully, I can have a demo URL back to you tomorrow or the next day.

**Comment by spdev3000** [comment]
Yes, you are correct assuming that I leverage the "short" (2 chars) unit.

**Comment by Westbrook** [comment]
@spdev3000 I've updated https://support-px--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--pixels with the knowledge that Spectrum asks us not to show units while editing the input:

![image](https://user-images.githubusercontent.com/1156657/132878304-760db5aa-ba16-4fb0-a03e-760b0e9248ea.png)

This update now applies to all `unit` values, so you will see it occur in the "inches" demo as well: https://support-px--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--units&args=disabled:false;readonly:false;quiet:false;value:!undefined;placeholder:;min:!undefined;max:!undefined;step:!undefined

This will not change the updates to what keystrokes will or won't be accepted as applied in #1514.

I've also expanded the documentation site to include a section on "Units not included in `Intl.NumberFormatOptions`" that can be seen here: https://support-px--spectrum-web-components.netlify.app/components/number-field

Can you confirm that you also were interested in seeing polyfilled support for graphics units in the `<sp-slider>` element as well? We should be able to leverage roughly the same pattern that is applied above to that as well. If you feel like we've gone in the right direction on this it's highly likely that we can get this update included in the release we discussed for Monday.

**Comment by spdev3000** [comment]
Sounds great, thx @Westbrook - yes please also apply this to the formatOptions of the `<sp-slider>/<sp-slider-handle>` elements.

**Comment by Westbrook** [comment]
Reviewing these in the Slider patter a la:
- https://support-px--spectrum-web-components.netlify.app/storybook/?path=/story/slider--px
- https://support-px--spectrum-web-components.netlify.app/storybook/?path=/story/slider--two-handles-pt
- https://support-px--spectrum-web-components.netlify.app/storybook/?path=/story/slider--three-handles-pc
