### ISSUE TITLE
[Feat]: Allow styling of an <sp-action-group> to affect slotted <sp-action-button>s

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#1751]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-group, sp-action-button

### Description of the requested feature

Let's say we have a project we're creating where we want to allow buttons within an action group to be slotted in by a consumer, and we want those buttons to have a particular style or attribute, like `quiet`. 

```
<sp-action-group quiet>
    <slot name="invite"></slot>
    <slot name="share"></slot>
    <slot name="info"></slot>
</sp-action-group>
```

Ideally, when the consumer goes to slot in those `<sp-action-button>` elements in their implementation, the `quiet` attribute would apply to the buttons they've slotted because they would be part of the `<sp-action-group>`. However, this does not occur. It would be great if we could get those styles/attributes to trickle down to the action-buttons so that the styles don't have to be applied individually.

Interestingly, this doesn't seem to apply to attributes other than `quiet` and `emphasized`. 

### Mockups or screenshots

Implementation with current vs expected behaviour (using quiet attribute as an example): https://webcomponents.dev/edit/esO7bStw93lhCr2Kc0FB/

**Comment by Westbrook** [comment]
One possible approach to this: https://webcomponents.dev/edit/ULnM2TO0R0vQM615sZBU/src/index.stories.js

The use of:
```
const buttonDescendants = Array.from(el.querySelectorAll(`:scope > ${this._buttonSelector}`));
```
Means that we're locking some content out of the management, but that is going to _usually_ be content that might be in an overlay:
```
<sp-action-group>
  <overlay-trigger>
    <sp-action-button slot="trigger"></sp-action-button> // <= included, yay!
    <sp-action-button slot="longpress-content"></sp-action-button> // <= included, boo...
    <sp-popover slot="click-content">
      <sp-action-button></sp-action-button> // <= excluded, yay!
    </sp-popover>
  </overlay-trigger>
</sp-action-group>
```
I think the likelihood of `<sp-action-button slot="longpress-content"></sp-action-button>` style overlay content is very low and something that we shouldn't be suggesting anyone does, and the likelihood of overlay content having Action Buttons within it would be very high, so excluding it will be good. 

Previously, the code was likely grabbing the content inside of the overlay, so that button not being negatively effected in a benefit of this change. I'm not sure there's a system safe way to exclude the `slot="*-content"` elements in this context from this code path.

What other edge cases should we attempt to manage (or document) as we address this?

**Comment by castastrophe** [comment]
I think the issue could be addressed at roughly line 355 of `packages/action-group/src/ActionGroup.ts`:

```js
const buttons = [
    ...this.querySelectorAll(this._buttonSelector),
] as ActionButton[];
```

This line is querying the component's light DOM for the `sp-action-button` tag. Since the "light DOM" of the component might be in the shadow DOM of another component, we might also want to catch slots with assignedNodes matching the same query.

```js
const slots = [...this.querySelectorAll('slot')];
slots.filter((slot) => {
    const nodes = slot.assignedNodes();
    nodes.filter((node) => node.nodeType == Node.ELEMENT_NODE && node.tagName === this._buttonSelector);
    return nodes;
});
```

Then we could merge the resulting slotted content with the buttons.

**Comment by Westbrook** [comment]
I do like simpler! The test case for this approach will likely be an intersection of https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/action-group-tooltips--selects-single and the OP example. If it's able to cover both, :shipit:!

**Comment by castastrophe** [comment]
Just saw some of your demo code uses `assignedElements({flatten: true});` and I didn't know that existed! 🤯
