### ISSUE TITLE
[Bug]: Allow sp-picker to change when rendering with new menu labels

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#1893]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-picker

### Expected behavior

If a menu item has a label change after the picker was rendered, we should allow the label to update as well (if based on a currently selected menu item)

### Actual behavior

The label attribute changes, as well as the internal sp-menu-item label, but what you see on screen does not update

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

https://webcomponents.dev/edit/msStOl89omAAl2v2k3VR

`
import { LitElement, html, customElement, TemplateResult } from "lit-element";
import "@spectrum-web-components/picker/sp-picker.js";
import "@spectrum-web-components/menu/sp-menu.js";
import "@spectrum-web-components/menu/sp-menu-item.js";
import "@spectrum-web-components/menu/sp-menu-divider.js";

@customElement("my-picker")
export default class MyPicker extends LitElement {
  protected itemname = 'Soon';
  protected render(): TemplateResult {
    return html`
      <sp-picker quiet label="A label">
        <sp-menu-item value="0">
          Immediately
        </sp-menu-item>
        <sp-menu-item value="1">
          I'm already using them
        </sp-menu-item>
        <sp-menu-divider></sp-menu-divider>
        <sp-menu-item value="2">
          ${this.itemname}
        </sp-menu-item>
        <sp-menu-item value="3">
          As part of my next project
        </sp-menu-item>
        <sp-menu-item value="4">
          In the future
        </sp-menu-item>
      </sp-picker>
       <button @click=${() => { this.itemname = 'My item changed'; this.requestUpdate()} }>Change my item</button>
    `;
  }
}
`

**Comment by OpportunityLiu** [comment]
I'm using `repeat()` to render a list of `<sp-menu-item>`s for selections of a picker, whose `textContent` is loaded from an array. While the array changes, the template string used by `repeat()` is not changed, so lit will reuse current `MenuItem` instances and change their `textContent`.

Same issue for `<sp-tabs>`. As a workaround, I made different template strings for different contents, to make lit invalidate cache.

```ts
        return html`<div id="right">
            ${this.renderNameEditor()}
            <sp-tabs
                class="tabs"
                @change=${(ev: Event) => (this.rightTab = (ev.target as Tabs).selected)}
                selected=${this.rightTab}
                >${selected
                    ? html`<sp-tab has-selection value="args" label=${t`args`}></sp-tab>
                          <sp-tab has-selection value="style" label=${t`style`}></sp-tab>`
                    : html`<sp-tab value="args" label=${t`variables`}></sp-tab>
                          <sp-tab value="style" label=${t`canvas options`}></sp-tab>`}
            </sp-tabs>
            ${content}
        </div>`;
```
The only aim of the `has-selection` attribute is to make two template strings differ from each other, so that lit will re-render all `<sp-tab>`s instead of changing only `label` attribute,

**Comment by Westbrook** [comment]
@OpportunityLiu when using `repeat()` I’d suggest using the signature with a `keyFn` which should ensure that you do not recycle elements for multiple items: https://lit.dev/docs/templates/directives/#repeat Hopefully, that will reduce the effects of this situation. 

I’m surprised that you’re seeing this in the Tabs element, so that’s very much for the report. This will go a long way in helping prioritize this!

**Comment by OpportunityLiu** [comment]
That's what happened in `sp-tabs`, the `slotchange` event will not fired when child attributes changes. And the tab indicator will not re-position. Due to the limitation of `slotchange`, I'd guess such situation would appear here and there in the lib. Unless you changed to use `MutationObserver` and observe child attribute changes (even descents in some situation).

![image](https://user-images.githubusercontent.com/13471233/140930962-06a5ab9d-b318-41d5-a9e9-d0582e71b169.png)
![image](https://user-images.githubusercontent.com/13471233/140930987-a8fa2f1c-a221-4c5a-ac69-fc2872f97a18.png)

**Comment by OpportunityLiu** [comment]
For the `sp-picker`, if you changed the `textContent` of the selected `sp-menu-item`, the content of the picker will not change.

![image](https://user-images.githubusercontent.com/13471233/140931737-b5ac8996-b831-4efc-8639-881a631f1720.png)
![image](https://user-images.githubusercontent.com/13471233/140931890-ab2c6450-b02a-49ba-8059-236533636ce8.png)
Until you open the popover of the picker
![image](https://user-images.githubusercontent.com/13471233/140931797-39895087-04ea-428a-ab87-bc081c83d3ee.png)


In fact, even if you empty the `sp-picker`, the content of the picker will also not change. So I think it's not caused by element recycling.
![image](https://user-images.githubusercontent.com/13471233/140932468-65072819-6101-4bda-89d6-a66051594737.png)

**Comment by Westbrook** [comment]
@OpportunityLiu bumped the Tabs conversation out into another issue. Looking to submit a PR for the Picker issue a little later today.
