### ISSUE TITLE
[Bug]: split-button stops showing its menu after an open->close

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#1894]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

split-button

### Expected behavior

Clicking the down arrow on an `<sp-split-button>` repeatedly should open and close its menu.

### Actual behavior

Clicking the down arrow on an `<sp-split-button>` opens and closes its menu once, then never again.

Clicking the down arrow, then selecting a new option from the menu each time, works as expected.

### Screenshots

https://user-images.githubusercontent.com/364501/139466363-bcff516b-4c2e-487c-80ff-8890ed3b35ac.mov

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/split-button/
2. Click on a split button's down arrow repeatedly

**Comment by sorinsarca** [comment]
Seems to work fine [in this fiddle](https://jsfiddle.net/0s2xko8e/)

Also, on [https://opensource.adobe.com/spectrum-web-components/components/split-button/](https://opensource.adobe.com/spectrum-web-components/components/split-button/) all split buttons that also have the `left` attribute work fine. However, it is hard to debug because it appears that source maps aren't good.

**Comment by adixon-adobe** [comment]
Looks like this is also an issue for Action Button
