### ISSUE TITLE
[Bug]:  Editable slider won't display value when step changes from 0 to 1

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#1981]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider

### Expected behavior

When using a `editable` slider with `value=0` and initial `step=0` a slider gets rendered - but then if the step value gets updated after some time to `step=1` I would expect to have that value (0) displayed in the Numberfield of that editable slider.
It works for non-editable slider where the value gets displayed, but fails on the version with Numberfield.

### Actual behavior

No value is displayed in the Numberfield when using value=0 and step=0 --> step=1

### How can we reproduce this issue?

see https://webcomponents.dev/edit/YXbAlAI268hChQzlEam3

### Sample code that illustrates the problem

https://webcomponents.dev/edit/YXbAlAI268hChQzlEam3

**Comment by Westbrook** [comment]
Interesting.

Can you share more on why you make `step=0` to start? This seems like it shouldn't be something we allow, and doing so would seem like the simplest way to fix this, today in your code but also in library. 

If your use case requires that feature we can certainly dig deeper into what's going on with the Number Field, where this issue seems to arise, specifically: https://webcomponents.dev/edit/ZyczGMGa6kzjGqfY34GL/src/index.ts?p=stories

**Comment by spdev3000** [comment]
I connect it via bindings to a 3rd party lib where initially step=0 is set. I do prevent this now on our component level, but would be good to have at least the Numberfield shown the `0` when step is updated to something !== 0
