### ISSUE TITLE
[Bug]: sp-tray with sp-dialog is too large

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#2303]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

tray

### Expected behavior

Tray with dialog inside should not be this large.

### Actual behavior

The tray is larger than it should be. There is some problem with the `.tray width` CSS property because disabling it in dev tools fixes this issue.

### Screenshots

![image](https://user-images.githubusercontent.com/1174072/169699982-4883ea33-2dc7-4445-ad1b-c2748508ea64.png)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/tray/#dialog
2. Click on 'Toggle tray'

**Comment by Westbrook** [comment]
We'll confirm with the design team, but we ran into this from the other side recently, and I actually think that in this context the Dialog should be sized to match the Tray so that the Tray is always the same size regardless of content. The design team will likely correct us both and then we'll get a fix out for this, soon.

Thanks for submitting!
