### ISSUE TITLE
[Bug]: ActionMenu in a Dialog causes issues

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-web-components#2314]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

actionmenu dialog

### Expected behavior

An ActionMenu within a dialog should work normally

### Actual behavior

Dialog moves in the page when the dialog opens.
Screen reader also behaves strangely (not sure if this is a side effect of the rendering)

### Screenshots

https://user-images.githubusercontent.com/1724479/170126882-d69577fd-92ee-4368-b3a1-82954b2889e9.mp4

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/PagXACe2UJGCLYkdzWRe
2. Click on Toggle Dialog
3. Click on More Actions
4. Observe

**Comment by Westbrook** [comment]
Looks like this is due to this code in the story:
```
  <style>
    active-overlay[placement="none"] {
      position: static;
    }
  </style>
```
That's from our demo project 🙈 but I'm not sure why it was there. Likely from a situation in the past where we didn't fully manage Dialog? But, I can't guarantee that.

It wasn't previously in our actually docs site, and I've removed it on our end in https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/MLYDVWpWhNxJZDW3Ywqq/src/index.stories.js?p=stories If you do so, too, then you should no longer have this issue. If you're still having trouble here, please feel free to reopen this issue and let us know about other things you're noticing in this context.
