### ISSUE TITLE
[Bug]: Tooltip appears on its own after closing the model using double trigger <overlay-trigger> and one have type: model

### ISSUE THREAD

**Issue by mopandit** [adobe/spectrum-web-components#2317]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Canvas

### Expected behavior

On closing the sharesheet tooltip should not apear on it's own.

### Actual behavior

Everytime Sharesheet is dismissed after performing any operation such as inviting users, changing permissions or just cancelling out of popup after opening, is displaying the Share tooltip for blue Share button. The tooltip will just stay there forever until clicked to dismissed.

Same issue can be repro into the story book for type model: [this demo](https://no-tooltip-receives-focus--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--double-trigger&args=type:modal)

### Screenshots

More info: https://jira.corp.adobe.com/browse/CANVAS-9819

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

This way it can be reproduced in horizen platform:

1. Create a Canvas doc or open any existing one
2. Click on Share button to open Sharesheet popup
3. Add an invitee and click send. Or choose to change user permission for any existing invitee in the list
4. Dismiss sharesheet popup
5. Notice Share tooltip would appear on its own and stay there, even though mouse cursor is not on that button.

**Comment by Westbrook** [comment]
Hi @mopandit thanks for the issue. In that [case that you've outlined](https://no-tooltip-receives-focus--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--double-trigger&args=type:modal) there is invalid consumption of the `<overlay-trigger>` that we will not be making changes to Spectrum Web Components to support. If you _absolutely_ need to have the dialog and tooltip functionality segmented in this way, we do vend the imperative API that `<overlay-trigger>` is powered by which should allow you to control this functionality however you see fit for you application: https://opensource.adobe.com/spectrum-web-components/components/overlay/

While reviewing this situation we did find a related issue in `<overlay-trigger type="modal">` that _may_ have prevented you or others from leveraging a single trigger element, due to an error in the way that it opened Tooltip content. This is being addressed in #2318 which should be ready to ship, shortly.
