### ISSUE TITLE
[Bug]: Can't import workflow icon as generic template tag

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#2419]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

icons-workflow

### Expected behavior

It should be possible to import the raw SVG icon.

### Actual behavior

I'm not getting the same result as described in the docs (2nd example of "Extended use cases"). Instead of getting the `<svg>` element, I'm getting `TemplateResult`.

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Import icon
2. Do `console.log`
3. See different result

### Sample code that illustrates the problem

```ts
import { AbcIcon } from '@spectrum-web-components/icons-workflow/src/icons.js';

console.log(AbcIcon());
```

**Comment by Westbrook** [comment]
If you're getting Template Result, it's likely because you've already set the stateful value of `customTemplateLiteralTag` to `html` from Lit. This happens as a side effect of importing icons through the default export or `/src/index.js`, as well as when importing defined icon elements: e.g. `<sp-icon-abc>`, etc.

See in isolation: https://studio.webcomponents.dev/edit/FhNjP7QTmTNZ7brOTceJ/src/index.ts?p=stories

I've never tried to _unset_ it in TS, which will likely complain about this, but you can do:

```
import { setCustomTemplateLiteralTag } from '@spectrum-web-components/icons-workflow/src/custom-tag.js';

setCustomTemplateLIteralTag(undefined);
```

This would allow the internals to default back to the internal raw string literal processor.

Or if you want to be "more correct", you could set it to a raw string literal processor of your own:

```
const tag = function (
    strings: TemplateStringsArray,
    ...values: unknown[]
): string {
    return values.reduce(
        (acc: string, v, idx) =>
            (acc as string) + (v as string) + strings[idx + 1],
        strings[0]
    );
};
```

The API is not particularly tuned for going back and forth, so if you had a good use case for this, we could look at changes in the future, but for now, I will close this.

**Comment by davidkudera** [comment]
It's happening on a new project where I just installed the icon packages without configuration or changing them. So maybe there is some additional logic in the decision between `SVG` and `TemplateResult`?

But anyway, thanks for your suggestions, I'll try them.

**Comment by Westbrook** [comment]
If you can repro, I can take another look.
