### ISSUE TITLE
[Color Area] wrong Color Handle color when only providing x and y attributes to Color Area

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#2688]
### Expected Behaviour
When providing x and y attributes to the sp-color-area the handle position changes and internal color will be updated - thus reflecting in the different color-handle color

### Actual Behaviour
When providing x and y attributes to the sp-color-area handle position changes but internal color won't be updated 

### Reproduce Scenario (including but not limited to)
open https://studio.webcomponents.dev/edit/OhmxNozsXaiZ9O4F0aPW
compare start color of both Color Areas

#### Sample Code that illustrates the problem
This might be solvable by simple adding:
```
this.colorController.applyColorFromState()
```
in set x() and set y()

**Comment by Westbrook** [comment]
Interesting. I wouldn't say that you _supposed_ to use the `x` and `y` properties directly, but we're clearly not doing anything to prevent you from doing so...

If you think this one liner corrects this, happy to accept a PR on this! Would that be enough to remove the need to the downstream work you are doing in your project?

Separately, and likely longer term, we are looking at https://colorjs.io/ as a replacement for TinyColor, which looks to have higher quality/fidelity color transforms, and hopefully aligns more closely with a future browser standard in color management in JS. Not sure if that effect this request in any way, but wanted to keep you up to date.

**Comment by Westbrook** [comment]
Making some progress on the alternative approach that should give us better fidelity to the color spaces we use today as well as open up a whole load of [new color spaces](https://colorjs.io/docs/spaces.html) that we haven't previous leveraged. This specific issue is hopefully shown as fixed in https://color-js--spectrum-web-components.netlify.app/storybook/?path=/story/color-area--applied-vales, lots of work on insuring a smooth transition between the two versions, but progress.

**Comment by Westbrook** [comment]
Fixed by #4240
