### ISSUE TITLE
[Bug]: Checkbox with size AND tabindex=-1 exceeds callstack

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#2710]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Checkbox, likely others

### Expected behavior

`<sp-checkbox size="s" tabindex="-1">Chekbox</sp-checkbox>` should just work.

### Actual behavior

Causes am exceeds call stack error.

### How can we reproduce this issue?

https://studio.webcomponents.dev/edit/jeIGAXHMUrTp6hGMquoD/src/index.ts?branch=tab-index%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories

**Comment by bangank36** [comment]
@Westbrook I can reproduce the issue on the lastest version, the setter 'tabindex()' caused this stack error but I not quite sure what the class Focusable do, do you mind to give some background info tips, thanks
https://github.com/adobe/spectrum-web-components/blob/729adb1b84bcb1f66bfa21229784b89454ffd7c4/tools/shared/src/focusable.ts#L77

I was looking at this issue mentioned about the tabIndex=-1 issue happens, but there is no clue yet...
https://github.com/flatpickr/flatpickr/issues/1730

**Comment by bangank36** [comment]
[This line](https://github.com/adobe/spectrum-web-components/blob/729adb1b84bcb1f66bfa21229784b89454ffd7c4/tools/shared/src/focusable.ts#L107) on the tabIndex setter will re-trigger the [size setter](https://github.com/adobe/spectrum-web-components/blob/bd429b26c284e65c83f494b129468fb20e277f82/tools/base/src/sizedMixin.ts#L64), making the loop happen, my suggestion is skip edit the tabIndex once we know it is equal -1, eg:
https://github.com/adobe/spectrum-web-components/blob/729adb1b84bcb1f66bfa21229784b89454ffd7c4/tools/shared/src/focusable.ts#L107

The condition is already `tabIndex === -1 || this.disabled`, I think we can get rid of the line above, what do you think? I removed it without issue, but maybe I missed something else

nit: Found a type `cange` in the comment https://github.com/adobe/spectrum-web-components/blob/729adb1b84bcb1f66bfa21229784b89454ffd7c4/tools/shared/src/focusable.ts#L105

**Comment by Westbrook** [comment]
Have you been able to confirm a _why_ the line you've pointed to triggers the `size` setter? It doesn't seem like it should, being it doesn't actually set `size`. Until we better understand the cause here, we shouldn't look to change any of the underlying code as it could have side effects in other contexts.

**Comment by bangank36** [comment]
Let me try to explain what I found...
First of all, the [CheckboxBase inherited Focusable](https://github.com/adobe/spectrum-web-components/blob/bd429b26c284e65c83f494b129468fb20e277f82/packages/checkbox/src/CheckboxBase.ts#L20) and [Checkbox inherited Size](https://github.com/adobe/spectrum-web-components/blob/bd429b26c284e65c83f494b129468fb20e277f82/packages/checkbox/src/Checkbox.ts#L93), that explains the connection between `size` and `tabIndex` attributes that cause this issue

Next, method [attributeChangedCallback()](https://github.com/lit/lit/blob/77544071eaed1c0bbf0447b9faa316dd244094c9/packages/reactive-element/src/reactive-element.ts#L1079) of  `@lit/reactive-element` ( which a dependency of this repo ) will be fired whenever we use `setAttribute` on the element

That will be the case which causes the issue
- On render the tabindex attribute is mapped to property on [set tabIndex(tabIndex: number)](https://github.com/adobe/spectrum-web-components/blob/729adb1b84bcb1f66bfa21229784b89454ffd7c4/tools/shared/src/focusable.ts#L76)
- Since we [manually set the tabIndex attribute](https://github.com/adobe/spectrum-web-components/blob/729adb1b84bcb1f66bfa21229784b89454ffd7c4/tools/shared/src/focusable.ts#L107) using `setAttribute` it will re-run the [attributeChangedCallback()](https://github.com/lit/lit/blob/77544071eaed1c0bbf0447b9faa316dd244094c9/packages/reactive-element/src/reactive-element.ts#L1079)
- Same happens [on size](https://github.com/adobe/spectrum-web-components/blob/729adb1b84bcb1f66bfa21229784b89454ffd7c4/tools/base/src/sizedMixin.ts#L64)
- I think it making an infinite loop that exceed the callstack

<img width="335" alt="image" src="https://user-images.githubusercontent.com/10071857/217614248-057a74a5-597a-4dcf-b701-61378a6f27fb.png">

**Comment by bangank36** [comment]
@Westbrook any thoughts on this? Thx

**Comment by Westbrook** [comment]
Recent changes to Checkbox seem to remove this situation from the repro link.
