### ISSUE TITLE
[Bug]: When using Switch or Checkbox component in a table row, exception occur when the Switch or Checkbox is clicked

### ISSUE THREAD

**Issue by monkeyjabs** [adobe/spectrum-web-components#2807]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Table, TableRow

### Expected behavior

No exception should occur when the Switch or Checkbox component is clicked. The TableRow component should account for other components that could trigger the `change` event in the `handleChange()` method.

### Actual behavior

`TypeError: Cannot read properties of undefined (reading 'checked')`

### Screenshots

Example
![PixelSnap 2022-12-20 at 11 49 54](https://user-images.githubusercontent.com/4380525/208754128-5c1a052c-7140-4d33-b89d-4fac302b56f4.png)

error
![PixelSnap 2022-12-20 at 11 49 05](https://user-images.githubusercontent.com/4380525/208753966-01b1dff5-2254-48f7-bfa7-8079b2fb9bdd.png)

### What browsers are you seeing the problem in?
Any Browser

### How can we reproduce this issue?

1. Go to this playground example: https://studio.webcomponents.dev/edit/U6z97bJLW2cZahcDZ4Mh/src/index.ts?p=stories
2. Click on Switch toggle
3. Observe the error on screen and console

### Sample code that illustrates the problem

```
<sp-table>
  <sp-table-head>
      <sp-table-head-cell>Flag</sp-table-head-cell>
      <sp-table-head-cell>Value</sp-table-head-cell>
  </sp-table-head>
  <sp-table-body>
    <sp-table-row>
        <sp-table-cell>Enable</sp-table-cell>
        <sp-table-cell>
            <sp-switch>
                Value
            </sp-switch>
        </sp-table-cell>
    </sp-table-row>
  </sp-table-body>
</sp-table>
```

**Comment by bangank36** [comment]
Hello @monkeyjabs, I'm new contributor here and would like to chime in
I think the issue is caused on this line https://github.com/adobe/spectrum-web-components/blob/a227f511afef4e23d1a328465d7c5e6da4ae0199/packages/table/src/TableRow.ts#L57

As soon as a `sp-table-row` found a `sp-checkbox` on its cells, it considers the cell as `sp-table-checkbox-cell` right away which will lead to the error above

**Comment by Westbrook** [comment]
@bangank36 if you wanted to take a stab at a PR for this, we'd be happy to accept one. Feels like we need to brand the checkbox in `sp-table-checkbox-cell` so it can be "well known" at the `sp-table-row` level so that we can disambiguate the `change` events that pass through it.

**Comment by bangank36** [comment]
Hi @Westbrook, thanks for the tips, I'd like to discuss more on this:

- > brand the checkbox in sp-table-checkbox-cell so it can be "well known" at the sp-table-row

Do you suggest we should do something similar to 
https://github.com/adobe/spectrum-web-components/blob/a227f511afef4e23d1a328465d7c5e6da4ae0199/packages/table/src/TableRow.ts#L71

- > so that we can disambiguate the change events that pass through

I'll try to see if we can conditionally set the `bubble` prop when the parent of the checkbox is `sp-table-cell`
https://github.com/adobe/spectrum-web-components/blob/a227f511afef4e23d1a328465d7c5e6da4ae0199/packages/checkbox/src/CheckboxBase.ts#L42

**Comment by Westbrook** [comment]
The first is close, and a possibility. We could take `event.composedPath()` and look for an `sp-table-checkbox-cell` in the array and that would make our checkbox "well known".

I was thinking of putting an ID on the `sp-checkbox`, but a middle ground where we make an early return when `typeof event.target.checkbox === 'undefined'` is likely enough. This prevents any array walking and would ensure that the target we are listening to is "shaped like an `<sp-table-checkbox-cell>`" before allowing the event callback.

With the above, we wouldn't need to worry about trying to mangle the `bubble` on events that we do not own.

**Comment by bangank36** [comment]
More update on this

> we wouldn't need to worry about trying to mangle the bubble on events that we do not own

You are correct on this, since this issue is persisted whenever we put any component which triggered a `change` event into an ordinary `sp-table-cell`, eg: 
```
<sp-table-cell>
    <sp-color-area></sp-color-area>
</sp-table-cell>
```

> middle ground where we make an early return

I tried the same approach with your suggestion but using optional chaining to [stop event propagation](https://github.com/adobe/spectrum-web-components/blob/a227f511afef4e23d1a328465d7c5e6da4ae0199/packages/table/src/TableRow.ts#L54), otherwise it will bubble to `sp-table` and [shout similar error ](https://github.com/adobe/spectrum-web-components/blob/bd429b26c284e65c83f494b129468fb20e277f82/packages/table/src/Table.ts#L366) 😅

```
if ( ! event.target?.checkbox ) {
        event.stopPropagation();
}
```

Then there is another issue to deal with, when the `sp-checkbox` (or any component with `change` event ) is in the same row with the `sp-table-checkbox-cell`,. eg:

```
<sp-table-checkbox-cell>
       Row Item Alphas
</sp-table-checkbox-cell>
<sp-table-cell>
       <sp-color-area></sp-color-area>
        <sp-switch>
             Value
       </sp-switch>
        <sp-checkbox indeterminate>228 Selected</sp-checkbox>
</sp-table-cell>
```

https://user-images.githubusercontent.com/10071857/217425933-6407fa74-ab9c-40b2-bd2b-fe86b8afa6e6.mov

**Comment by Westbrook** [comment]
The `!event.target?.checkbox` value points to events that "we do not own", and as such we should not alter the bubble dynamics of those events by using `stopPropagation()`.

Great catch on finding this up a level! We should use the well known check in both places so that we are only responding to events from targets we intend and are not altering events from targets that are not well known.

**Comment by bangank36** [comment]
I'll try that and update accordingly

**Comment by bangank36** [comment]
@Westbrook, I propose a PR for the `event.target?.checkbox` issue, kindly have a look.
I also have another concern which I mentioned earlier about how to make a `sp-table-checkbox-cell` & `sp-switch` ( or `sp-color-area`, actually any component which fire a `change` event will see this issue ) can co-exist in the same `tableRow`. Currently, when I click on the `switch` is also select/deselect the whole row and change the checked status of the `sp-table-checkbox-row`. See recording on https://github.com/adobe/spectrum-web-components/issues/2807#issuecomment-1421950981
According to line below, as soon as it detects there is a `sp-checkbox` in `tableRow`, it will skip trigger click on the `checkboxCell` of the same row, but I found out not only `sp-checkbox` cause this issue, but also other components such as `sp-switch`, `sp-color-area`... are needed to be checked too, but I think making it a list of ignore components is not the best practice, do you have any suggestion on this matter? Thanks 😊 
https://github.com/adobe/spectrum-web-components/blob/1575a58b09a210c2034c1f9f59042c6edd1dfc33/packages/table/src/TableRow.ts#L90

**Comment by bangank36** [comment]
Update for the checkboxCell issue https://github.com/adobe/spectrum-web-components/pull/2919/commits/66b34bd318f1c5afb319e74d7267c16a4ae8f912
https://github.com/adobe/spectrum-web-components/blob/66b34bd318f1c5afb319e74d7267c16a4ae8f912/packages/table/src/TableRow.ts#L87
I update the logic for `handleClick` so that the checkboxCell is triggered click event only when the target is `sp-table-cell`, so if the target is other components with `change` event, the click handler will be return without manually click on the checkboxCell

**Comment by bangank36** [comment]
Any thoughts @Westbrook
