### ISSUE TITLE
[Bug]: previously selected element's tooltip(self-managed) appearing on switching browser tabs, without hover on element.

### ISSUE THREAD

**Issue by ananpal** [adobe/spectrum-web-components#2943]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tooltip

### Expected behavior

on switching tabs the tooltips should not appear without hover over element.

### Actual behavior

on switching tabs the previously selcted tooltip is appearing; without hover over element.

### Screenshots

https://user-images.githubusercontent.com/29448061/220373842-0ea814bc-4e1f-46d0-a604-27e6466caf57.mov

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Hover over a element which has self managed sp-tooltip 
2. switch the browser tab
3. switch to original tab again

**Comment by Westbrook** [comment]
This is due to the element in question receiving focus when entering the page, which is expected behavior for the current API. 

It's possible that we revisit this functionality in future iterations and in concert with new browser APIs, so I'll leave this open as an `enhancement`. For now, I do not expect to see any work done against this, however.

**Comment by najikahalsema** [comment]
This works as intended.

**Comment by aneeshg2** [comment]
Hi @Westbrook   @najikahalsema 
Can you please help me understand more as to why it was closed as expected behaviour.

Can the tooltip be displayed on hover only and not on every focus situation .. would it be an involved change in SWC code to decouple tab switch from display of tooltip ?

This issue currently affects both photoshop web and illustrator web.

**Comment by najikahalsema** [comment]
Hi, this is expected behaviour because the interaction is always needed to be hover AND focus for accessibility purposes. If one is unable to use a mouse to hover, then they're locked out of that interaction. Perhaps you could work with @dineshy87 @majornista who are working on an a11y audit at the moment and could chat with you about alternatives/why decoupling this behaviour could cause problems.
