### ISSUE TITLE
[Bug]: Overlays break usage of dynamic viewport height

### ISSUE THREAD

**Issue by benjamind** [adobe/spectrum-web-components#3187]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay

### Expected behavior

Should be able to use dynamic viewport units with overlay system.

### Actual behavior

Using the overlay system breaks dynamic viewport units.

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by jinpae** [comment]
We aren't using dvh and #3188 seems to break our example app because of the missing unit resulting in `calc(100% - 0))`. Maybe I'm missing something, but is the expectation for apps that don't use dynamic view height to override `--swc-body-margins-block` to keep the previous behavior? We'd like to fix the issue without updating our example app code if possible.

**Comment by Westbrook** [comment]
That was originally our intent. There were a couple of reports of the same, and we'll have a reversion of that change in the next release.

**Comment by Westbrook** [comment]
The code previously in question is no longer leveraged when delivering this functionality. Feel free to open a new issue if you still have trouble in this area.
