### ISSUE TITLE
[Feat]: expand Action Group management to include Action Menu children in Action Bar

### ISSUE THREAD

**Issue by l3vi-7** [adobe/spectrum-web-components#3531]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Action Bar

### Description of the requested feature

Action Menu is not currently an accepted child of Action Bar. Expanding the Action Group management that is internally leveraged by Action Bar to include Action Menu would enable clients to use Action Menu with slot "buttons" and may also help resolve the Menu overlay overlap issue. (Please refer the attached image)
![image (6)](https://github.com/adobe/spectrum-web-components/assets/42098011/4df356d8-116a-4f38-b715-66fcd0945a34)

**Comment by Westbrook** [comment]
In lieu of #1719 I'm a bit remiss to say it, but likely the right path here is to update `protected _buttonSelector = 'sp-action-button';` to `protected _buttonSelector = 'sp-action-button, sp-action-menu';` and then add some new tests leveraging `sp-action-menu`s or some `sp-action-menu`s to the existing tests to ensure appropriate coverage.

_Some_ of the functionality here won't be available until #3530 is complete, so it's probably a good idea to start there.

@Rajdeepc, could you look at who on the team might be able to pick this up?

**Comment by najikahalsema** [comment]
> Good morning team ... I have a few questions about the action group [pr](https://github.com/adobe/spectrum-web-components/pull/3780). With the latest comment from Westbrook (ain't he supposed to be off the grid for a few weeks ) it looks like he wants to extend Action Group to support Action Menu as children too. Currently action group is written in a way to support action buttons only and if we want to extend it for action m**enu I'd need more clarification on certain implementation details** and apart from this, a major doubt that I have is with the consumption of Action Menu inside of the Action Bar - If we have a Action Menu inside of an Action Group in the Action Bar that we cannot tab into the Action Menu (cz Action Menu and Action button both are a part of a group).  and leads to the following error 
![image](https://github.com/adobe/spectrum-web-components/assets/44980010/cbbbc6a2-2a41-41c4-88cc-1caaba943ca2)


Hey Tarun. I would agree that in order to make this a complete fix, we need to think about including the action menu as part of the action group. What clarifications are you looking for on the implementation details?

The other question I have is what you mean by "If we have a Action Menu inside of an Action Group in the Action Bar that we cannot tab into the Action Menu (cz Action Menu and Action button both are a part of a group)"? Where is that error coming from? Is it an accessibility error or something else?

**Comment by Rajdeepc** [comment]
@najikahalsema Tarun has shared a video of his questions and observations. We can discuss on this further.

https://github.com/adobe/spectrum-web-components/assets/8790510/ffc64c95-6579-48c6-89f3-bb1606702bc2
