### ISSUE TITLE
Doc site links to individual components 404

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#357]
### Expected Behaviour

Copying a link on the doc site & sharing works.

### Actual Behaviour

Links like this 404: https://opensource.adobe.com/spectrum-web-components/components/tooltip

### Steps to Reproduce

1. Go to https://opensource.adobe.com/spectrum-web-components/
2. Go to the tooltip page.
3. Copy the url & share

Result: page 404s.

**Comment by Westbrook** [comment]
@cuberoot do you think it's possible to add a step to the processing of #312 whereby we create copies of the output `index.html` for each of the URLs that should be accessible?

Maybe not directly related, but benefiting of the work that goes into the population of Lunr data?

**Comment by cuberoot** [comment]
@Westbrook The normal way to tackle this issue is to create a `404.html` file that redirects. However, the file doesn't seem to get picked up. I suspect that something is different because we are being served from `https://opensource.adobe.com/spectrum-web-components`.

I will look into your suggestion of creating copies of the index.html.
