### ISSUE TITLE
[Feat]: Adjust overlay top/left positioning to re-align with trigger when sizes change 

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3809]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay

### Description of the requested feature

Currently if users open a popover with dynamical content where the height changes - and that popover is in an overlay triggered by some button (or other element) with top alignment - when the height changes it doesn't update the alignment to the trigger. Thus resulting in either covering the trigger (when the element height enlarges - or moving the bottom line of the popover away - when the height shrinks).
Same probably happens with left-positioning and dynamical width changes.

See screens:
1st example:
Popover in sp-overlay has some accordion in it, first collapsed state:
<img width="303" alt="Screenshot 2023-11-16 at 10 17 49" src="https://github.com/adobe/spectrum-web-components/assets/29090947/ea752e67-765f-4b7f-910d-9b2370235c65">

Then the accordion-items opens and the popover fully hides the trigger:
<img width="285" alt="Screenshot 2023-11-16 at 10 17 55" src="https://github.com/adobe/spectrum-web-components/assets/29090947/dfc22961-2532-48d4-ad7d-cf90fe34ce9b">

---------------
2nd example
Popover starts with open accordion item and aligns correctly:
<img width="249" alt="Screenshot 2023-11-16 at 10 18 02" src="https://github.com/adobe/spectrum-web-components/assets/29090947/09a7b141-6153-49e2-b680-dddd14071403">

Now accordion-item is closed, trigger is not aligned anymore:
<img width="291" alt="Screenshot 2023-11-16 at 10 18 07" src="https://github.com/adobe/spectrum-web-components/assets/29090947/41f4f168-fa28-49a8-83b6-9d3d9e5cedcf">

### Mockups or screenshots
Example: https://studio.webcomponents.dev/edit/ZZkbLM8jiPFVfb7zuz9g/src/index.ts?p=stories

**Comment by spdev3000** [comment]
See: https://studio.webcomponents.dev/edit/ZZkbLM8jiPFVfb7zuz9g/src/index.ts?p=stories

**Comment by Westbrook** [comment]
[This story](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/overlay--accordion) is _supposed_ to explain this, but the work that was previously done to support this was no longer needed in that specific arrangement after V2, so was removed.  We should definitely update it to be more closely inline with the version you've shared so that it is more apparent how to approach usage like this.

From the outside, this can be controlled [as follows](https://studio.webcomponents.dev/edit/QPrWQLRuaaYglDFKNbG3/src/other.ts?p=stories), by either knowing when the element should change size (in the case of `sp-accordion`, the `sp-accordion-item-toggle` which feels pretty poorly named years later) or by letter the browser tell you when it changed via the Resize Observer (very clumsily applied in the demo).

Whether this should be "built-in" or not is a different question. That we've gotten this far without it feels like it certainly shouldn't be the default, but if you have further thoughts on how/where/if this should be added to the native API, please expand below 🙏🏼

**Comment by Westbrook** [comment]
> Whether this should be "built-in" or not is a different question.

@spdev3000 thoughts?

**Comment by spdev3000** [comment]
I'd personally love to get the opportunity to have this general resize-changed and position update behavior covered by internal overlay functions, (for example triggered by an `auto-resize` attribute) - such as the "auto" function in floating-ui lib etc.
We can still work around with that examples you provide us, but mid-long term I would see this as a built-in option. (Whether ResizeObserver is used or not - is a different question).

**Comment by Westbrook** [comment]
Tracking this for the conversation around adding this natively to the API: https://github.com/floating-ui/floating-ui/issues/2645
