### ISSUE TITLE
[Bug]: Action Menu opens on bottom of page in mobile browser screen dimensions

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3822]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Action Menu

### Expected behavior

Action Menu would open next to trigger on mobile browser screen resolutions in https://opensource.adobe.com/spectrum-web-components/components/action-menu/

### Actual behavior

Action Menu overlay opens on bottom of the page

### Screenshots

![Screenshot 2023-11-22 at 16 41 45](https://github.com/adobe/spectrum-web-components/assets/29090947/578b59b6-d5d1-434d-8208-626feec3da50)
![Screenshot 2023-11-22 at 16 46 36](https://github.com/adobe/spectrum-web-components/assets/29090947/ccf033b2-7bb1-493b-b5ba-7895d3a61cf5)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
The issue here is that sizing of the popover rule in the Picker is overriding the Tray rules as this should display like:

<img width="479" alt="image" src="https://github.com/adobe/spectrum-web-components/assets/1156657/f1f05e85-6159-4080-9cce-7362ab66fa31">

Adding the following to our local styles should correct the issue:

```
sp-tray#popover {
  width: 100%;
}
```

Would you be able to submit a PR?
