### ISSUE TITLE
[Feat]: Tabs: Automatically bring the selected tab into view

### ISSUE THREAD

**Issue by Rocss** [adobe/spectrum-web-components#3987]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tabs

### Description of the requested feature

Given that I have the multiple tabs, which are wrapped in `sp-tabs-overflow`, and I already have a selected tab when the component is rendered, if the selected tab is not into view, it is confusing for users to understand what tab is selected.
You have to use the right arrow to scroll and discover the selected tab.

Introducing an optional attribute which scrolls to the selected tab would improve the user experience in use cases with small viewports, or large number of tabs.

### Implementation notes or ideas

`sp-tabs` component already knows what is the selected tab. The implementation would modify the `willUpdate` method (https://github.com/adobe/spectrum-web-components/blob/main/packages/tabs/src/Tabs.ts#L305) to verify if the selection is into view. If the child is not into view, scroll it into view (either at the center, or the start/end of the `sp-tabs-overflow` view space).

**Comment by Westbrook** [comment]
Questions:
- Should `<sp-tabs-overflow>` _always_ "autoscroll"?
- Is it possible to leverage https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView so that we don't need to use `offsetLeft` and `clientWidth` which require a paint to leverage?
- If we use `scrollIntoView()` is it possible to move the majority (or all) of this work into `<sp-tabs-overflow>`?
- In theory, we could move the work from `_waitForChildrenToUpdate` into `getUpdateComplete` and support both this use case with a simple `await tabs.updateComplete` and remove the need to override `manageAutoFocus` to begin with.

**Comment by Rocss** [comment]
> Should `<sp-tabs-overflow>` _always_ "autoscroll"?

I don't have a strong opinion on this. As a user I do prefer for it to scroll, as I can view the tab that's selected without me needing to do anything.
I do think it should be at least optional and if it were to be optional, the name can also be improved into something that would tell you it is only _initially scrolling_. What do you think?

> Is it possible to leverage https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView so that we don't need to use `offsetLeft` and `clientWidth` which require a paint to leverage?

Yep, it can be changed to `selectedTab.scrollIntoView({ inline: 'center' });`, I worked around with your suggestions in https://github.com/Rocss/spectrum-web-components/commit/71f2b8ddb97c1a8efea82580b9a4a9768e56874a

**Comment by Westbrook** [comment]
Fixed in https://github.com/adobe/spectrum-web-components/pull/4032
