### ISSUE TITLE
[Bug]: Picker inside overlay opens at wrong position

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#4010]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay, Picker

### Expected behavior

When a picker component is used inside an overlay (dialog, popover) it should align the open overlay correctly.

### Actual behavior

Picker content doesn't align when that picker is inside another overlay.

### Screenshots

![Screenshot 2024-02-06 at 17 58 18](https://github.com/adobe/spectrum-web-components/assets/29090947/71818444-587e-41cf-99e0-b56b17e80f98)

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/szkt5zjgqqL3P0seGvVr/src/index.ts?p=stories
2. Click on button to open first overlay
3. Click on the picker inside that overlay
4. See alignment of open content

**Comment by Westbrook** [comment]
FYI: until we release this update, the only way this would be encountered in an actual application is if it hadn't previously locked a ceiling version of the `@floating-ui/*` dependencies (e.g. was brand new or otherwise broke it's lock). We'll have the reflooring of the dependency available soon, but not likely until next week or so.
