### ISSUE TITLE
[Feat]: sp-number-field repopulate field after deletion

### ISSUE THREAD

**Issue by cdvu1** [adobe/spectrum-web-components#4109]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-number-field

### Description of the requested feature

Currently, removing the number in the number field leaves the number field blank. It would be nice if the number field could repopulate to either the previous value, or the default value (ex. 0).

**Comment by TarunAdobe** [comment]
Hello @cdvu1. I discussed the idea of having a `default-value` for the number-field component with the team. We felt that since the `number-field` component is a controllable by the consuming application, having a reset to `default-value`behaviour can be easily created by listening to the `@change` event on the number-field component. I have added an example of the same in our doc site in this [PR](https://github.com/adobe/spectrum-web-components/pull/4698). Let me know if this helps :)
