### ISSUE TITLE
Support "download" attribute on sp-link

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#508]
### Expected Behaviour
When I use <sp-link> and set the href to a URL formatted data string for downloading a file, I'd like to specify the filename as I do with the <a> tag.

### Actual Behaviour
The download attribute is ignored and the file naming is out of my control

**Comment by Westbrook** [comment]
Ben, this sounds like a solid addition for us. Please confirm that I understand correctly that by default you can do:
```
<a download="filename.html" href="blob">Download this blob</a>
```
in order to control the local name by which the blob is downloaded as, and you like to be able to do the following with `sp-link`:
```
<sp-link download="filename.html" href="blog">Download this blob</sp-link>
```
If so, could I interest you in putting together a PR?

Relying on `ifDefined` to ensure that the `download` attribute wasn't errantly added to the interior `a` should catch the "missing" case via the current shadow DOM comparison test, and adding a second test with `download` present that ensures that it _does_ gets set, either manually or with DOM comparison will help us to ensure it sticks around as intended.

**Comment by bengfarrell** [comment]
Hey sorry - I didn't see this until now! I'll try to find the time!
