### ISSUE TITLE
Overlay Trigger doesn't trigger if browser focus is lost

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#511]
So FIRST of all - I did say I'd say I could submit a PR if I found something. I'm not - because it's hecka complicated from the looks of it. There's lots of logic here to unravel and lots of use cases it looks like you want to support for me to even think about how you'd want to fix. But I can tell you exactly what's wrong

### Expected Behaviour
Popover trigger should launch consistently

### Actual Behaviour
When browser loses focus with popup open, the trigger never works again

### Reproduce Scenario (including but not limited to)
Use the popup contents (such as an internal button) to launch a color picker or local file dialog. Even putting a debugger breakpoint on an internal button or similar should be enough to lose focus and repro the bug

#### Platform and Version
0.7.3

#### Logs taken while reproducing problem

So basically, the issue seems to be this:

1. User clicks button to trigger popup

2. Popup is triggered, and has an internal button to launch a file dialog or color picker. Meanwhile, Internally the "click-content" slot is moved out into the document at large

3. User clicks internal popup menu button to activate OS level dialog (color picker or file dialog), which removes focus from the browser. Either clicking this button or interacting with the color/file dialog causes mouseclick events to fire which is handled by the OverlayStack class and automatically closes the overlay.

4. Closing the overlay triggers a sequence of events. The "hideAndCloseOverlay" function is at the heart of the issue here. Inside, there is an async "overlay.hide" function. Internally, this function gracefully hides the menu over time. Being async, it will block cleanup with "overlay.remove()" until "overlay.hide()" completes. 

5. There is a timing issue I can't figure out here. Removing the "overlay.hide()" function fixes the entire situation. I can only imagine its a timing issue.

6. Going deeper, the issue might lie in Active-Overlay. The function "returnOverlayContent()" successfully sets the element "this.overlayContent" slot attribute successfully to "click-content". However, when recreating the bug, "returnOverlayContent()" successfully sets slot attribute, but then immediately runs once more where it doesn't set the slot attribute successfully because "this.originalSlot" is undefined. It's looking like something about this behavior is triggering 2 overlay hides in a row. Perhaps the second hide is triggered while the first await hide animation is in progress and things don't get properly cleaned up?

**Comment by Westbrook** [comment]
Thanks for the detailed report here @bengfarrell! Would you happen to be able to share a repo/stackblitz/etc with the outlined use case ready for reuse? It's possible that this issue, as well as some clarity on how to handle focus loss in the context of an overlay, can both be addressed from such a reproduction.

I have a feeling, from the outside, that the situation here comes from the use of `requestAnimationFrame` to manage the add/remove of the overlay, which won't (IIRC) be called while the file browser is open stealing focus from the tab. That should theoretically queue a "close" action when the file browser is opened (that can't be completed, yet) and then a second "close" action when the overlay is still available upon returning focus (that gets queued behind the previous one), then the `requestAnimationFrame` resolves which enacts both "close" actions, one correctly and one not. If that is the case, it might be that `rAF` isn't the correct timing against which to enact these commands, or it's possible that we should cache a "close" action so that while it's _incomplete_ another can't be created, or I could be barking up the wrong tree.

Whether this gets us going down the right path or not, there would stand the question, should the overlay close in this case? Losing focus might correctly close a "hover" overlay, but a "click" overlay might deserve to stay open in this case, seeing this situation in real-time will help clarify what is the "right" functional path forward here. It'll also be useful to see if there is some way that we can recreate this situation without the file browser UI so that we could bake it into a unit test and protect this use case in the future.

**Comment by bengfarrell** [comment]
Ha, I seriously thought I was losing my mind. I couldn't repro for a sec there when I cobbled something quickly together. Not sure what happened, but finally knocked it down to this use case which should show the bug in action pretty well.
 
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script type="module">
        import {Theme} from "@spectrum-web-components/theme/lib/index";
        import {OverlayTrigger} from "@spectrum-web-components/overlay/lib/index";
        import {Popover} from "@spectrum-web-components/popover/lib/index";
        import {Button} from "@spectrum-web-components/button/lib/index";
        import {render, html} from 'lit-html';

        export default class BugRepro extends HTMLElement {
            connectedCallback() {
                this.attachShadow( {mode: "open"});
                render(html`<p>Click the "popopen" button to open the popup. Then click "click me" to open a file dialog. Choose a file or cancel. Now, the popup no longer opens</p>
                            <overlay-trigger id="trigger" placement="bottom" offset="0">
                                <sp-action-button slot="trigger" quiet>+POPOPEN+</sp-action-button>
                                <sp-popover dialog slot="click-content" direction="bottom" open>
                                    <button @click=${e => this.shadowRoot.querySelector('input').click()}>click me</button>
                                </sp-popover>
                            </overlay-trigger>
                            <input style="display: none" type="file" id="file-upload" multiple accept="image/*">`, this.shadowRoot);
            }
        }

        customElements.define('bug-repro', BugRepro);
    </script>
    <script>
        window.process = window.process || {};
        window.process.env = window.process.env || {};
        window.process.env.NODE_ENV = window.process.env.NODE_ENV || 'production';
    </script>

</head>
<body>

<bug-repro></bug-repro>

</body>
</html>`

**Comment by bengfarrell** [comment]
Weird, for some reason I had trouble reproducing on a simple test case, so had to work backward from my component that I had trouble with. Here's a gist showing a simple use with the bug:
https://gist.github.com/bengfarrell/6b2d9ef5411b4612bff43f3a0c559618

**Comment by Westbrook** [comment]
Very short term fix, if you're looking for something soon:
```
<overlay-trigger id="trigger" placement="bottom" offset="0">
  <sp-action-button slot="trigger" quiet>+POPOPEN+</sp-action-button>
  <sp-popover dialog slot="click-content" direction="bottom" open>
    <button @click=${e => this.shadowRoot.querySelector('input').click()}>click me</button>
    <input style="display: none" type="file" id="file-upload" multiple accept="image/*">
  </sp-popover>
</overlay-trigger>
```
Doing this will ensure that you aren't "clicking outside" of the `click-content` when opening the upload browser, which should mitigate and hopefully nulify the conent porting issue. The only addition will be managing the closing of the overlay content in some other fashion. Hope to have something more wholistic on this issue before too much longer.
