### ISSUE TITLE
sp-icon size attribute should be deprecated

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#669]
### Expected Behaviour
The sp-icon size attribute as it exists should be deprecated or removed as it doesn't map to an actual Spectrum design concept. It also defaults to the small size which isn't the default size that should be used in controls.

Instead we should make the following changes (likely with support from SpectrumCSS):

* Default the size to the equivalent of "s" in the current implementation (18x18 or 22x22 depending on the scale).
* Use an overridable variable for the default size, which will better prepare us for t-shirt sized components. E.g. we might have a large size for action button which needs the icon to be larger as well. This should "just work" if you use sp-icon. 

### Actual Behaviour
We support a size attribute that doesn't make much sense to support at this point. There are 2 upcoming spectrum initiatives that should supersede what's here: t-shirt sizing for controls & icon sizing for things with a wider range of sizes like avatars.

**Comment by Westbrook** [comment]
The sizes that are currently supported come from https://unpkg.com/browse/@spectrum-css/icon@2.1.1/dist/index.css This package doesn't seem to have a beta release for a 3.0 version, which tends to mean that Spectrum CSS isn't currently testing breaking changes for their new version. It seems from the conversations I've seen you have with the team that Spectrum is planning changes to the spec, but it's unclear when/if those changes will make it into `@spectrum-css/icon` as most of the Spectrum changes seem to be in relation to a icons inside of patterns rather than icons deployed individually (so much so that neither the Spectrum public nor contribution sites seem to reference icons not otherwise contained in a larger patter).

If the timeline there is unknown or non-short, is there a specific use case that we can focus on supporting better at the SWC level or a specific way to could message a transition period to keep the RIO of using `<sp-icon>` today high while reducing any refactor costs that might be required to get to the new version of Spectrum and Spectrum CSS when it solidifies at a later date?

**Comment by Westbrook** [comment]
Can you help me clarify the expected behavior you've listed here? The code seems to currently default to `size="m"` https://github.com/adobe/spectrum-web-components/blob/main/packages/icon/src/icon.ts#L36-L37

Based on the latest version of the Spectrum CSS packages, this works out to be `24px X 24px` and `30px X 30px` in the medium and large scales, respectively.
- https://unpkg.com/browse/@spectrum-css/icon@2.1.1/dist/index.css
- https://unpkg.com/browse/@spectrum-css/icon@2.1.1/dist/index-lg.css

By that, would you expect the default to then be `size="s"` instead?

**Comment by adixon-adobe** [comment]
Yes -- updated the description to say "equivalent of "s" in the current implementation". I clearly have trouble keeping the current behavior straight in my head...

I'll also open an issue on Spectrum CSS about this, and hopefully we can use that to help answer your timeline question (you just did a good amount of my homework on that so thanks!).

**Comment by adixon-adobe** [comment]
@Westbrook I filed https://github.com/adobe/spectrum-css/issues/753 -- does that sound right to you?

**Comment by Westbrook** [comment]
At current, the simplified Spectrum CSS of this pattern still _includes_ a size mechanism: https://github.com/adobe/spectrum-css/blob/tshirt-size-workflow-icon-continue/components/icon/workflow-icons.css#L21-L65 If that persists, would the right path for us be to switch this into a fully opt-in attribute rather than defaulting to `size='m'` within our code?

**Comment by Westbrook** [comment]
@adixon-adobe want to make sure you saw this. Not sure the right path forward once the Spectrum CSS PRs there land. 

@lazd, have any thoughts on this?

**Comment by lazd** [comment]
My gut says we still need to be able to specify the size of an icon manually, because some dev somewhere is going to need it. 

However, for consistency's and maintainability's sake, if the icon size is always set contextually, things Just Work™ and changes can be made to the sizing of icons via tokens without a manual markup change all the way downstream in a consumer product.

After all, a workflow icon should NEVER just live on its own! It should at least be inside of a Quiet ActionButton if it's clickable. If there's some other case where workflow icons are used outside of components, then yeah, we def need sizes. If not, then maybe we don't, and maybe #1070 is da wae, and maybe it's not overreach for components to customize icon sizes...

**Comment by lazd** [comment]
Now, as far as Spectrum official icon sizes, we've been in a holding pattern for like 3 years on that. Last I heard, @badimon had a proposal for a new workflow icon size, removing the border, making things 20x20 by default, etc. I don't know where that's at, and I don't think we got all the assets for it, but @jianliao may have more insight.

**Comment by badimon** [comment]
He did have a plan to expand the frame size of workflow icons (18 by 18 px to 20 by 20 px) earlier this year, but this plan has been retired – indefinitely. Our team (Spectrum) goal was to anticipate future needs from the Icon team but we will rather wait for concrete needs from the Icon team to take action since this is a big amount of work that requires a strong justification in the first place.

**Comment by jianliao** [comment]
I agree with @lazd. Those manual icon size CSS classes should still be maintained. It could be helpful for the framework like angular spectrum to progressively upgrade to CSS variable icon size mechanism in the future.

**Comment by Westbrook** [comment]
Not "deprecated" but de-emphasized. Let us know if you think we should do further work here.
