### ISSUE TITLE
Can sp-tab manage the content?

### ISSUE THREAD

**Issue by jameslan** [adobe/spectrum-web-components#676]
### Expected Behaviour
```html
<sp-tab label="tab1">
<div>tab1 content</div>
</sp-tab>
```
To show "tab1 content" when `tab1` is selected.
In another word, manage the visibility of contents of tabs.

### Actual Behaviour
No default slot supported.

**Comment by Westbrook** [comment]
Currently, users need to manually associate `sp-tab` elements to their _content_, usually via something like:
```
      <sp-tabs selected="1" direction="vertical">
        <sp-tab label="Tab 1" value="1"></sp-tab>
        <sp-tab label="Tab 2" value="2"></sp-tab>
        <sp-tab label="Tab 3" value="3"></sp-tab>
        <sp-tab label="Tab 4" value="4"></sp-tab>
      </sp-tabs>
      <div class="content">
        <div section="1">
          <p>This is content for the first tab.</p>
        </div>
        <div section="2">
          <p>This is content for the second tab.</p>
        </div>
        <div section="3">
          <p>This is content for the third tab.</p>
        </div>
        <div section="4">
          <p>This is content for the fourth tab.</p>
        </div>
      </div>
```

However, beyond this a good amount of manual aria attributing is needed to properly associate the content for screen readers. We should structure an approach where the elements are able to deliver the desired aria attributes and DOM structure so that this can be more easily attainable by the end user; either via a wrapper pattern like `sp-dialog-wrapper` or additional elements, or API changes to the current elements.

**Comment by davidjgonzalez** [comment]
@Westbrook do i have to write my own show/hide hooks for the content structure you describe in your post?

I implemented my content it that manner and all `.content div[section=*]` show all their contents regardless of the tab i click..?

To by honest, im not clear what the "manual association" is in your example even -- is it just `sp-tab[value]` to `.content div[section]`?

**Comment by Westbrook** [comment]
Hi @davidjgonzalez using the `selected` attribute as outlined above (and leveraged in our documentation site) with CSS that looks like:
```
[section] { display: none; }
[selected="1"] + .content [section="1"] { display: block; }
// etc...
```
Would allow you to make this manual association in CSS: e.g. https://webcomponents.dev/edit/2JFFTBPXfCZpePD0wk58/src/index.ts

You could separately leverage the `change` event outlined in the [API tables](https://opensource.adobe.com/spectrum-web-components/components/tabs/api) to manage this association in JS a la: https://webcomponents.dev/edit/Y6mTicns34oBqMaHDhTV/src/index.ts

We are looking into a more encapsulated version of this, which is part of why we've not gone deeper on explicit usage patterns in the documentation. Low usage has made it difficult for us to raise the priority here, but I'd love to hear more about your use case to see how we can support it more directly!

**Comment by davidjgonzalez** [comment]
@Westbrook quick follow-up, your CSS suggestion worked great (for my small UI).

It might be worth noting on the `sp-tabs/sp-tab` documentation that you need to provide your own tab-content toggling, providing the notes from your reply. 

The most challenging part for me when dealing w this was understanding the limits of the `sp-tabs/sp-tab` web components as this wasn't abundantly clear in the docs, so instead of thinking about how I would create my own tab-content toggling effect, I spent time trying to understand how to unlock it int he web component (I wasn't sure if I was missing an npm dependency, sometimes wasn't loading properly, etc.)

**Comment by Westbrook** [comment]
Moving the conversation for this topic to #1280 where we are discussing more broadly the changes needed to support a more broadly accessible `sp-tabs` patterns and the `role=tabpanel` content referenced in this issue.
