### ISSUE TITLE
Dropdowns with scrollable menu content could open smarter

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#910]
### Expected Behaviour
Dropdowns with really long menu content should open above the menu if there's more room there, or scroll the page down a bit.

### Actual Behaviour
On all browsers they open down. On Safari it's scrolling our test page down so 1 cell is visible if there's no room below, but on FF/Chrome isn't not doing that.

**Comment by adixon-adobe** [comment]
This is definitely a polish issue -- getting performance for larger menus improved seems way more important. My team's got good testers though so I'll keep passing these on!

**Comment by Westbrook** [comment]
Can you share some screenshots of this situation to ensure replication in developing a PR here?

**Comment by Westbrook** [comment]
is this something that we're able to recreate in the documentation site? If so, we've just update the version of PopperJS that we're using and it would be great to revisit this issue there: https://opensource.adobe.com/spectrum-web-components/ Otherwise, we'll have an updated release to test against your local demo repo soon.

Beyond that, maybe we're talking about a `min-height` value here? I wonder if you could test with something manually applied to the `<sp-menu>` element in your test suite?

**Comment by adixon-adobe** [comment]
Here's a couple of screenshots of the menu. So far it looks like if I add a min-height to the menu, it'll open above when you click it. But if I scroll down the menu will immediately switch to the bottom regardless of whether it renders offscreen, so there's a little more at play here.

I can only reproduce this if the menu scrolls though. Which gave me the idea to try setting a fixed `height` as well. That prevents the issue entirely, which seems like a clue.

<img width="239" alt="Screen Shot 2021-01-13 at 10 55 34 AM" src="https://user-images.githubusercontent.com/48841507/104483578-e4a99200-558d-11eb-83f6-c8a68764b32b.png">
<img width="540" alt="Screen Shot 2021-01-13 at 10 50 36 AM" src="https://user-images.githubusercontent.com/48841507/104483584-e70bec00-558d-11eb-97ca-049e0302f443.png">
