### ISSUE TITLE
Adding input type to TextField

### ISSUE THREAD

**Issue by leangseu** [adobe/spectrum-web-components#926]
### Expected Behaviour
`TextField` should have default behavior for changing input type such as `text|email|tel|password|url|number`. Currently adding, it seems inappropriate because `TextField` multiline is `textarea`. I propose that we should separate text field and text area field.

### Actual Behaviour
I cannot have password TextField by default.

**Comment by Westbrook** [comment]
@leangseu Thanks for creating this issue! My apologies for not getting back to you sooner with feedback. There are a number of factors at play that make this specific change both very important and somewhat less straight forward.

There is the idea that right now the `sp-textfield` element can be overloaded to be both an `<input type='text' />` and a `<textarea />`, which has both its own specific issues as well as the idea that a `textarea` cannot (should not?) have the types that you've outlined here. My initial reaction is that to properly support this feature we will likely need to separate the two and vend them as separate packages going forward so that users of one do no pay the tax of the other (likely `input` users paying for `textarea` and not using it), while still amortizing any cost across the two that we can. This implies a relationship of a `FieldBase => Textfield` and `FieldBase => Textarea` relationship that will deserve some added investigation.

What's more, I really agree with broader community statements that batching the `type` attribute into the `<input />` element was a bad idea and furthers the situation outlined above for every one of the features that you'd like added via this issue. This doesn't mean that these shouldn't be added, because I agree that they should, just that we need to do so intentionally. Should we create an `sp-textfield-password`, `sp-textfield-telephone`, etc. for each type? Maybe. There will likely be long term feature customization for each specific `type` that we'd like to keep corralled in a single location, and reduce the change of unneeded functionality making it to the final bundle.

Beyond that, the thought/work that is going into #475 has yet to fully crystalize on a broadly applicable pattern of label application. One possible path forward could involve requiring the actual form input for a custom form element to be in the light DOM to easily relate to a label, which would also allow for users to directly manage the `type` field of such an input, obviating any direct work here. While this seems like a sane path forward there are some specific realities around the selectors allowed in the `::slotted()` syntax that would require a good bit of tooling updates to support such a path.

There is much ambiguity here both as far as path forward and tooling needed to support it. Do you have any thoughts on the above or ideas on what might allow for the support of the features you're requesting without creating a likelihood for breaking changes in the near future?

**Comment by davidkudera** [comment]
There is already a `<sp-number-field>` so it would probably make more sense to create a new `<sp-password-field>`. 

I'm looking for a web components UI library to use in a new dashboard I'm going to work on and I noticed that Vaadim components went in the same direction. They have `<vaadin-password-field>` - https://vaadin.com/components/vaadin-password-field/html-examples/password-field-demos

**Comment by pjcalvo** [comment]
Hi all.

Is there an approach to use a type="password" field as today?
