### ISSUE TITLE
Difference between Spectrum Web Components and Coral Spectrum

### ISSUE THREAD

**Issue by elrumo** [adobe/spectrum-web-components#933]
### Expected Behaviour
It's not an issue, but I wasn't sure where to ask.  What is the difference between the Spectrum Web Components and [Coral Spectrum](https://opensource.adobe.com/coral-spectrum/documentation/)? Maybe some clarification with the differences could be added to the documentation, or even a list of all the Spectrum flavours there are available, i.e. React Spectrum, Coral Spectrum, Spectrum CSS....

**Comment by Westbrook** [comment]
Thanks for the question @elrumo, it's a good one. All of these projects are web implementations of the Spectrum Design system: https://spectrum.adobe.com/. At their site they do the work of outlining all the flavors and attempt to manage the current availability of patterns in those flavors (a difficult undertaking that we're working to support them better on when it comes to SWC). Holistically, all of the projects flow from there, so it feels like the right place for this sort of documentation, but I'm open to hearing good places to reference this ecosystem more clearly on ours. 

From Spectrum Design, a few layers down from there is Spectrum CSS, which is a visuals only web implementation of the design system in CSS and is the basis for Spectrum Web Components, React Spectrum, and I believe Coral Spectrum (though I'm not 100% sure on this point). Each does their own work to bring Spectrum Design to contexts in which they are applicable, React applications for React Spectrum, highly (at least as advertised) customizable, light DOM only application for Coral Spectrum, and the web in general, leveraging encapsulation through shadow DOM in Spectrum Web Components. Each has their own strengths and weaknesses in line with the technical decisions and feature offerings they've pursued that would be difficult to get into systematically on any one implementations documentation site.

Do you have thoughts on things about Spectrum Web Components in specific that you'd like to know more about or to be introduced specifically on our project site? We're always looking for better ways to empower new users from the start with both documentation ("Getting Started" section coming soon) and [education](https://opensource.adobe.com/spectrum-web-components/guides/developing-components), and look forward to better fulfilling that promise for users like you!

**Comment by undavide** [comment]
@Westbrook thanks for the clarification 

> We're always looking for better ways to empower new users 

Google pointed me here as I'm trying to make up my mind, as I'm re-designing from scratch an old website. As I'm already using Spectrum in the context of Adobe UXP plugins, I though to be already well equipped: I was wrong... :-)

My web project is based on Gatsby, so at first I was looking at the [Adobe Gatsby Theme Parliament](https://github.com/adobe/gatsby-theme-parliament) where there are templates for various Adobe projects (documentation site, platform site, etc). But they're using MarkDown too extensively to my own taste and level of understanding of the inner mechanisms, so I've decided to start from scratch with something simpler and adapt it to Gatsby.

I've then run into React Spectrum. As I was trying to understand how to integrate that into my React components, and maybe using pieces of the Spectrum CSS that haven't been already implemented in React Spectrum, I've realized that while developing Adobe UXP plugins I am using Spectrum Web Components (available by default in the dev environment without any import statement). Having more familiarity with them, I was like heck these are the ones. 

But I'm having sort of a _senior-moment_: the Readme shows how to use yarn to build them, but – as opposed to Spectrum _pure_ CSS or even React Spectrum – I can't find instruction on how to import them into my project. Via npm I can easily find and install `"@adobe/react-spectrum"`, then, say, `import { ActionButton } from "@adobe/react-spectrum"`. What would be the equivalent for Spectrum Web Components?

Trying to answer this very question I've then run into Coral Spectrum, and instead of being happy for the richness of the ecosystem, at the moment I'm just quite confused. Any pointers are appreciated. Thanks!

**Comment by Westbrook** [comment]
Yes @undavide, if I understand correctly the UXP interface attempts to keep it's API in parity with Spectrum Web Components, so that could be a good cause to leverage the same in your other work. 

As for installing/importing Spectrum Web Components into your (non-UXP) project, every component should include documentation to this process (please feel free to submit an issue if we've somehow missed one). You can see this in action in the `sp-button` documentation page found here: https://opensource.adobe.com/spectrum-web-components/components/button Where you see both the installation instructions `yarn add @spectrum-web-components/button` and the import code: `import '@spectrum-web-components/button/sp-button.js';` as la:

![image](https://user-images.githubusercontent.com/1156657/96137802-16498900-0ecb-11eb-819e-4550cf98f89e.png)

Usage for every Spectrum Web Component that you've imported into your project in this way is as if it were native HTML: 

```
<sp-button variant="primary">This is David's awesome button.</sp-button>
```


This should be akin to what you've previously done in UXP, and the full API (attributes, properties, events, CSS Custom Properties) listing for each element is available via the "API" tab on each page: https://opensource.adobe.com/spectrum-web-components/components/button/api

Beyond that which flavor of Spectrum you choose to use has a lot to do with you periphery preferences and goals. As you've worked with UXP, working with Spectrum Web Components might be a good idea, if only for familiarity. You mentioned having worked with Gatsby, and if that's you cup of tea you might be better served by staying in the React community with React Spectrum. You mention not liking the preponderance of Markdown there, and while I can't say whether that's an actual requirement of those tools or not, I can say that you can but any HTML into markdown and that means that you can write both Spectrum Web Components and Coral Spectrum directly into markdown, which might reduce some complexity on your end. The one thing that I can say definitively is that while all three of the projects are based in some way on Spectrum CSS, the _pure_ CSS project does not ship functionality along side it's Spectrum implementation the way that Coral Spectrum, React Spectrum, or Spectrum Web Components does. For this reason, unless you're interested in investing a lot of time in effort in accessibility, interactivity, etc. I'd refrain from implementing that project directly and leave that hard work to teams committed to bringing those patterns fully baked to the broader community.

**Comment by undavide** [comment]
Thanks for the detailed answer @Westbrook – much appreciated 🙏🏻 You've shed some very welcome light on the topic.

I was used to install the entire library of components (e.g. with React Spectrum) at once with a single `npm` command, and then just import the needed components one by one, whereas here I also need to install each component separately instead – correct? Do you plan to release them as a unique package in the future?

As for Gatsby I'm in the middle of my learning curve – I've opened the code of some of the Adobe Themes and I'm sure in the long term `mdx` is handy, but where I am at now it just complicates matters. So I'll happily port my UXP knowledge to the web. Besides, Spectrum support in UXP is growing but still quite limited – I'm going to enjoy the abundance of available Components when targeting the browser :-) The React Spectrum project seems slightly behind in that sense.

> unless you're interested in investing a lot of time in effort in accessibility, interactivity, etc. I'd refrain from implementing that project directly and leave that hard work to teams committed to bringing those patterns fully baked to the broader community.

That thought has never crossed my mind :-)

**Comment by Westbrook** [comment]
We do vend `@spectrum-web-components/bundle` as a helper for getting started quickly. However, I would lean away from leveraging it actively in a production focused project in that once we go 1.0 (hopefully soon) relying on a bundle will force you to update ALL of your component usage for _any_ component you need to update, which can cause maintenance headaches down the line. It also will clash with certain build/package management tools/settings. Some of these tools REQUIRE that you directly depend on packages that you direct import, so starting with this practice from the beginning will also save you some headaches down the line.

**Comment by Westbrook** [comment]
This is a great conversation, however unless there is something specific that either of you feel belongs in our live documentation: https://opensource.adobe.com/spectrum-web-components or README.md or somewhere else I'd like to close this. Bringing conversations to life around specific missing documentation in new issues will be the best way for us to continue to shape the information we deliver to future SWC developers.
