### ISSUE TITLE
Clicking on Dropdown Padding results in "undefined" change

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#966]
### Expected Behaviour
If I click on a dropdown popup, but don't QUITE click on a menu-item (no highlight), but click on the sliver of padding, the dropdown should probably not commit a change because a menu item wasn't clicked

### Actual Behaviour
The click is accepted, the new value is "undefined", and an @change event occurs to the outside world

### Reproduce Scenario (including but not limited to)
Try any drop down, and position your mouse inside the sp-menu, but not inside an sp-menu-item. Make sure nothing gets highlighted. Now click. Undefined is accepted as a change

#### Platform and Version
master WC branch

**Comment by Westbrook** [comment]
Can you double check that you are still experiencing this in https://opensource.adobe.com/spectrum-web-components/? This was an issue that we did some work against somewhat recently, but there may be more "edge" to the case... I'm pretty sure there are no changes to the `Dropdown` or the `Menu` code in `main` so if it were fixed in the documentation site, you'd have it available in the most recent releases of each. 

In the case that you're still experiencing this, could you give slightly more explicit recreation steps as I'm not currently able to when clicking the tiny white sliver above the "Medium" option in this screenshot: 
![image](https://user-images.githubusercontent.com/1156657/96494255-1bcd0900-1214-11eb-9834-c59a9e902458.png)

**Comment by Westbrook** [comment]
Oh, also, side note, the `master` branch no longer exists. The current _default_ branch is `main`.

**Comment by bengfarrell** [comment]
Thanks! Looks fixed on the site. I thought it wasn't because I WAS testing on master and assuming it was the latest

**Comment by Westbrook** [comment]
Good to hear!

We've always very happy to get contributions, however. So, if you see anything else with the new latest...please don't hesitate. 🙏
